<section class="mx-3">

    <button type="button" class="btn btn-success mt-1 mb-2">   
       <a  class='text-light' href="<?=url('/admin/article/new')?>">
         nouvel article 
       </a>
    </button>
    <div class="table-responsive">   
        <table class="table table-bordered border-dark  table align-middle table-hover ">
            <thead >
            <tr>
            <th> #ID </th>
            <th> Title </th>
            <th> category</th>
            <th> Date</th>
            <th> Content </th>
            <th> Modify</th>
            <th> Delete </th>
            </tr>
            </thead>

            <tbody> 
                
                <?php foreach($articles as $article):?>
                    <tr>
                        <td> <?= intval($article['id_article'])?> </td>
                        <td> <?= htmlspecialchars($article['title'])?> </td>
                        <td><?= htmlspecialchars($article['label']) ?></td>
                        <td><?= (new DateTime($article['created_at']))->format('d/m/Y')?></td>
                        <td> <?= htmlspecialchars(mb_substr($article['content'],0,200))?> </td>
                        <td> 
                            <a href="<?=url('/admin/article/edit',['article_id'=>$article['id_article']])?>"> 
                               <button type="button" class="btn btn-primary btn-sm px-3">
                                   <i class="far fa-edit"> </i>
                               </button>
                        </td>

                        <td> 
                            <a href="<?= url('/admin/article/delete',['article_id'=>$article['id_article']])?>"> 
                               <button type="button" class="btn btn-danger btn-sm px-3">
                                  <i class="fas fa-times"></i>
                               </button>
                        </td>
                    </tr>
                <?php endforeach ?>   
            </tbody>         
        </table>
    </div>    
</section>        