
        <section class="my-3 mx-3">
           <article class="mx-auto d-flex flex-column ">
            <h3 class="text-center text-dark"> <?= ucfirst(htmlspecialchars($article['title']))?> </h3>
            <img src="<?= asset('upload/'.htmlspecialchars($article['image']) )?>"  class="img-fluid mx-auto" style="width:50rem;"/>
            <div>
               <p class="fw-lighter"><?= (new DateTime($article['created_at']))->format('d/m/Y')?></p>
               <span class="badge bg-light"> Category :<?= ucfirst(htmlspecialchars($article['label']))?> </span>  
            </div>
            <div> <?= htmlspecialchars($article['content']) ?></div>
           
            <!-- 
            <a href="/article?article_id=<?=$articleId+1?>"> Article suivant</a>
            -->
           </article>
        </section>
        <!--afficher les erreurs-->
        <section>
           <?php if(isset($errors) && !empty($errors)):?>
              <?php foreach ($errors as $error ):?>
               <div class="alert alert-dismissible alert-danger">
                 <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                 <p> <strong>Oh snap!</strong> <?= $error ?> </p> 
               </div>   
              <?php endforeach?> 
            <?php endif ?>     
        </section>

        <?php if((new App\Framework\UserSession())->isAuthenticated()):?>
          <!-- formulaire d'ajout de commentaire -->
          <form action="<?=url('/article',['article_id' =>$articleId])?>" method="POST">
            <label for="content"> Commentaire </label>
            <textarea  id="content" name="content"> </textarea>
            <button type="submit" class="btn btn-outline-success" value="valider"> valider </button>
          </form>
        <?php else: ?>
         <div class="alert alert-dismissible alert-danger">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <p> <strong> Oh snap! </strong> You have to be connected to add a comment, 
                  
                     <a  class="alert-link" href=<?= url('/signup')?>>Signup </a>
                     or
                     <a  class="alert-link" href=<?=url('/login')?>>Login</a>
            </p>         
         </div> 

        <?php endif ?>   

        <!-- AFFICHAGE DES commentaires -->
        <section>
           <h3 class="text-success"> <u> Commentaires </u> </h3> 
           <?php if($comments):?>
             <ul>
               <?php foreach ($comments as $comment ):?>
                 <li>
                     <h5> <?= htmlspecialchars($comment['firstname'] . ' ' .$comment['lastname'] )?></h5>
                     <p> <?= htmlspecialchars($comment['content'] )?> </p>
                     <span> le <?= (new DateTime($comment['created_at']))->format('d/m/Y')?> </span>
                     
                 </li>
               <?php endforeach?> 
             </ul>  
            <?php endif ?>     
        </section>
