
<section class="d-flex justify-content-around flex-wrap my-5 mx-1">
        <?php foreach($articles as $article):?>
           <article class="card border-primary mb-3" style="width: 25rem;height:32rem">
              <img src="<?= asset('upload/'.htmlspecialchars($article['image']) )?>" alt="" class="img-fluid" style="height:15rem;"/> 
              <div>
                  <h4 class="card-title" style='color:darkslategrey;'> <?= htmlspecialchars($article['title'])?> </h4>
                  <p><?= (new DateTime($article['created_at']))->format('d/m/Y')?></p>
              </div>
              <p> 
                  <?= htmlspecialchars(mb_substr($article['content'],0,200))?>...
                  <a href="/article?article_id=<?= intVal($article['id_article'])?>">lire la suite</a>
              </p>
           </article>
        <?php endforeach ?>   
 </section>



  