<section class="my-5">
    <?php if(isset($errors) && !empty($errors)):?>
            <?php foreach ($errors as $error ):?>
              <div class="alert alert-dismissible alert-danger">
                 <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                 <p> <strong>Oh snap!</strong> <?= $error ?> </p> 
               </div> 
            <?php endforeach?> 
      <?php endif ?> 

    <form action="<?= url('/contact')?>" method="POST" class="mx-auto" style="width: 400px;">
     <fieldset>
        <legend class="text-danger"><u> Contact Me 😊 ! </u> </legend> 

        <div class="form-group">
          <label for ="lastname" class="form-label mt-4">last name :</label>
          <input type="text" id="lastname" name="lastname"  class="form-control" >
        </div>

        <div class="form-group">
          <label for ="firstname" class="form-label mt-4">First name :</label>
          <input type="text" id="firstname" name="firstname" class="form-control" >
        </div>

        <div class="form-group">
          <label for ="email" class="form-label mt-4">Email :</label>
          <input type="email" id="email" name="email" class="form-control"  >
        </div>

        <div class="form-group">
          <label for ="message" class="form-label mt-4"> Message :</label>
          <textarea class="form-control" id='message' name='message'>   </textarea>
        </div>

        <button type="submit" name="envoyer" class="mt-2 btn btn-success"> send</button>
    </fieldset>
  </form>
</section>    