

<section>
  <h2> Login </h2>
  <?php if(isset($errors) && !empty($errors)):?>
        <?php foreach ($errors as $error ):?>
            <p><?= $error ?> </p>
        <?php endforeach?> 
  <?php endif ?> 
  <form action ="<?= url('/login')?>" method="POST">
  <div>
      <label for="email">Email</label>
      <input type="text" id="email" name="email"/>
    </div>
    <div>
      <label for="password">Password</label>
      <input type="password" id="password" name="password"/>
    </div>  

      <button type="submit" name="valider"> valider </button>
  </form>
<section>