
<section>
  <h2> Créez votre compte </h2>

  <?php if(isset($errors) && !empty($errors)):?>
        <?php foreach ($errors as $error ):?>
            <p><?= $error ?> </p>
        <?php endforeach?> 
  <?php endif ?>  

  <form method="POST" action="<?=url('/signup')?>">
    <div>
      <label for="firstname">firstName</label>
      <input type="text" id="firstname" name="firstname"/>
    </div>
    <div>
      <label for="lastname">LastName</label>
      <input type="text" id="lastname" name="lastname"/>
    </div>
    <div>
      <label for="email">Email</label>
      <input type="text" id="email" name="email"/>
    </div>
    <div>
      <label for="password">Password</label>
      <input type="password" id="password" name="password"/>
    </div>  

      <button type="submit" name="valider"> valider </button>
  </form>
</section>
