
<section class="mx-4 my-3">
  <h2 class="text-danger text-center"> SIGNUP </h2>

  <?php if(isset($errors) && !empty($errors)):?>
        <?php foreach ($errors as $error ):?>
            <div class="alert alert-dismissible alert-danger">
                 <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                 <p> <strong>Oh snap!</strong> <?= $error ?> </p> 
             </div> 
        <?php endforeach?> 
  <?php endif ?>  

  <form method="POST" action="<?=url('/signup')?>" class="mx-auto" style="width: 400px;">

  <fieldset>
        <div class="form-group">
          <label for="firstname" class="form-label mt-4">FirstName :</label>
          <input type="text" id="firstname" name="firstname" required class="form-control"/>
        </div>

        <div class="form-group">
          <label for="lastname" class="form-label mt-4">LastName :</label>
          <input type="text" id="lastname" name="lastname" required class="form-control"/>
        </div>

        <div class="form-group">
          <label for="email" class="form-label mt-4">Email :</label>
          <input type="text" id="email" name="email" required class="form-control"/>
        </div>

        <div class="form-group">
          <label for="password" class="form-label mt-4">Password :</label>
          <input type="password" id="password" name="password" required class="form-control"/>
        </div>  

        <button type="submit" name="valider" class="mt-2 btn btn-primary"> Signup </button>
    </fieldset>      
  </form>
</section>
