<?php if(!empty($errors)) : ?>
    <?php foreach($errors as $error) : ?>
                <p> <?= $error ?>
            <?php endforeach?>  
<?php endif ?>              
        <h3> Abonnez-vous à notre newsletter </h3>
         <form action="<?= url('/subscription')?>" method="POST">
             <label for="email"> saisir votre email</label>
             <input type="string" id="email" name="email"/>
             <button type="submit"> valider </button>
         </form>